icons = [
    {"name": "餐饮", "icon_name": "icon-canyin", "category_type": "expense"},
    {"name": "交通", "icon_name": "icon-jiaotong", "category_type": "expense"},
    {"name": "服饰", "icon_name": "icon-yiwu", "category_type": "expense"},
    {"name": "购物", "icon_name": "icon-gouwuche", "category_type": "expense"},
    {"name": "买菜", "icon_name": "icon-maicai", "category_type": "expense"},
    {"name": "教育", "icon_name": "icon-jiaoyu", "category_type": "expense"},
    {"name": "娱乐", "icon_name": "icon-yule", "category_type": "expense"},
    {"name": "运动", "icon_name": "icon-yundong", "category_type": "expense"},
    {"name": "生活缴费", "icon_name": "icon-fangzu", "category_type": "expense"},
    {"name": "旅行", "icon_name": "icon-lvyoudujia", "category_type": "expense"},
    {"name": "宠物", "icon_name": "icon-chongwu", "category_type": "expense"},
    {"name": "医疗", "icon_name": "icon-yaopin", "category_type": "expense"},
    {"name": "日用品", "icon_name": "icon-riyongpin", "category_type": "expense"},
    {"name": "发红包", "icon_name": "icon-hongbao", "category_type": "expense"},
    {"name": "修理", "icon_name": "icon-xiuliweihu", "category_type": "expense"},
    {"name": "其他", "icon_name": "icon-CombinedShape", "category_type": "expense"},
    {"name": "编辑", "icon_name": "icon-bianji", "category_type": "expense"},

    {"name": "工资", "icon_name": "icon-yinhangqia", "category_type": "income"},
    {"name": "收红包", "icon_name": "icon-hongbao", "category_type": "income"},
    {"name": "其他", "icon_name": "icon-CombinedShape", "category_type": "income"},
    {"name": "编辑", "icon_name": "icon-bianji", "category_type": "income"},

    {"name": "理财", "icon_name": "icon-touzizhongxin", "category_type": "other"},
    {"name": "接还款", "icon_name": "icon-xinyongqia", "category_type": "other"},
    {"name": "其他", "icon_name": "icon-CombinedShape", "category_type": "other"},
    {"name": "编辑", "icon_name": "icon-bianji", "category_type": "other"},

    {"name": "饮品", "icon_name": "icon-yinpin", "category_type": "none"},
    {"name": "化妆品", "icon_name": "icon-huazhuangpin", "category_type": "none"},
    {"name": "电影", "icon_name": "icon-dianying", "category_type": "none"},
    {"name": "淘宝", "icon_name": "icon-taobao", "category_type": "none"},
    {"name": "蚂蚁花呗", "icon_name": "icon-mayihuabei", "category_type": "none"},
    {"name": "京东白条", "icon_name": "icon-jingdongbaitiao", "category_type": "none"},
    {"name": "水果", "icon_name": "icon-shuiguo", "category_type": "none"},
    {"name": "礼物", "icon_name": "icon-liwu", "category_type": "none"},
    {"name": "游戏", "icon_name": "icon-youxi", "category_type": "none"},
    {"name": "书籍教材", "icon_name": "icon-shujijiaocai", "category_type": "none"},
    {"name": "汽车用品", "icon_name": "icon-qicheyongpin", "category_type": "none"},
    {"name": "家具", "icon_name": "icon-jiaju", "category_type": "none"},
    {"name": "家电", "icon_name": "icon-jiadian", "category_type": "none"},
    {"name": "婚姻恋爱", "icon_name": "icon-hunyinlianai", "category_type": "none"},
    {"name": "音乐娱乐", "icon_name": "icon-yinleyule", "category_type": "none"},
    {"name": "数码产品", "icon_name": "icon-shumachanpin", "category_type": "none"},
    {"name": "育儿", "icon_name": "icon-yuer", "category_type": "none"},
    {"name": "零食", "icon_name": "icon-lingshi", "category_type": "none"},
    {"name": "一般", "icon_name": "icon-yiban", "category_type": "none"},
    {"name": "借入", "icon_name": "icon-jieru", "category_type": "none"},
    {"name": "借出", "icon_name": "icon-jiechu", "category_type": "none"},
    {"name": "储值卡", "icon_name": "icon-chuzhiqia", "category_type": "none"}
]
